import Auth from "@/components/Auth/Auth";
export const metadata = {
  title: "iChat - Register/Login",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <Auth />
    </>
  );
}
